[package]
name = "hello_world"
version = "0.1.0"
authors = ["Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.76"
publish = false


[dependencies]
eframe = "0.28.1"
egui_extras = "0.28.1"
env_logger = "0.11.5"
